# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vT0nYg_FfgLU4k26dX3gYYKCiGQm4G04
"""

import pandas as pd
baza={

"FISH":[ "Aliyeva Rano", "Aliyev Ali", "Rahimov Aziz", "Xakimova Ozada", "Karimov Javohir", "Fozilova Sevara", "Bahodirova Feruza", "Dovronov Ahad", "Toirov Rahim", "Lutfullayeva Nargiza",],
"YOSHI":["11", '9', "13", "12", "16", "14", "10", "12", "15", "16", ],
"JINSI": ["qiz bola", "ogil bola", "ogil bola", "qiz bola", "ogil bola", "qiz bola", "qiz bola", "ogil bola", "ogil bola", "qiz bola"],
"QAYSI MAKYABDA OQISHI":["2-maktab", "prezident maktabi", "64-maktab", "12-maktab", "37-maktab", "1-maktab", "4-maktab", "23-maktab", "7-maktab", "56-maktab"],
"MANZILI":["Margilon shahri", "Fargona shahri", "Quva", "Toshkent", "samarqand", "jizzax", "navoiy", "Chust", "Nanay", "Bogdod",]

}
db=pd.DataFrame(baza)
print(db)

filtr = db[db['JINSI']==">= 12"]
print(filtr)

filtr=db[db['JINSI']=="qiz bola")&(db["YOSHI"]>'12')]
print(filtr)